### 장바구니에 추가
POST http://localhost:8080/shop/goods/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjM3NjU1NjczLCJleHAiOjE2Mzc3NDIwNzN9.XIR2djgDIZaflUGk4lZpq29qmX4WTiYCE08I6jyrBOlddtcziK8-MewmkpxEDoH_ctiWdTw0HErgP-o7o3qBlA

{
  "productCode": "70",
  "cnt": "4"
}

### 회원 장바구니 조회
GET http://localhost:8080/shop/goods/cart/member
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjM3NjcxMDQ4LCJleHAiOjE2Mzc3NTc0NDh9.7Kehwp-wjWEUUN472EejSkJ4gzHvRYAv2xBLKeGwAEx-LHS1h3-tdGGnYe2yJlgX5WEzznYuWXFJtLhFCl4t_Q

### 회원 장바구니 조회
DELETE http://localhost:8080/shop/goods/cart?productCode=95,70,
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjM3NjcxMDQ4LCJleHAiOjE2Mzc3NTc0NDh9.7Kehwp-wjWEUUN472EejSkJ4gzHvRYAv2xBLKeGwAEx-LHS1h3-tdGGnYe2yJlgX5WEzznYuWXFJtLhFCl4t_Q
