-- freqQuestion 기본 설정
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목1!','내용내용1!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목2!','내용내용2!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목3!','내용내용3!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목4!','내용내용4!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목5!','내용내용5!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목6!','내용내용6!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목7!','내용내용7!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목8!','내용내용8!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목9!','내용내용!9');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목10!','내용내용10!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목11!','내용내용11!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목12!','내용내용12!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목13!','내용내용13!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목14!','내용내용14!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목15!','내용내용15!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목16!','내용내용16!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목17!','내용내용17!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목18!','내용내용18!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목19!','내용내용19!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목20!','내용내용20!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목21!','내용내용21!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목22!','내용내용22!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목23!','내용내용23!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목24!','내용내용24!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목25!','내용내용25!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목26!','내용내용26!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목27!','내용내용27!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목28!','내용내용28!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목29!','내용내용29!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목30!','내용내용30!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목31!','내용내용31!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목32!','내용내용32!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목33!','내용내용33!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목34!','내용내용34!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목35!','내용내용35!');

-- notification 기본 설정
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목1','내용1','글쓴이1');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목2','내용2','글쓴이2');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목3','내용3','글쓴이3');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목4','내용4','글쓴이4');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목5','내용5','글쓴이5');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목6','내용6','글쓴이6');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목7','내용7','글쓴이7');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목8','내용8','글쓴이8');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목9','내용9','글쓴이9');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목10','내용10','글쓴이10');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목11','내용11','글쓴이11');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목12','내용12','글쓴이12');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목13','내용13','글쓴이13');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목14','내용14','글쓴이14');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목15','내용15','글쓴이15');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목16','내용16','글쓴이16');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목17','내용17','글쓴이17');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목18','내용18','글쓴이18');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목19','내용19','글쓴이19');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목20','내용20','글쓴이20');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목21','내용21','글쓴이21');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목22','내용22','글쓴이22');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목23','내용23','글쓴이23');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목24','내용24','글쓴이24');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목25','내용25','글쓴이25');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목26','내용26','글쓴이26');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목27','내용27','글쓴이27');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목28','내용28','글쓴이28');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목29','내용29','글쓴이29');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목30','내용30','글쓴이30');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목31','내용31','글쓴이31');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목32','내용32','글쓴이32');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목33','내용33','글쓴이33');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목34','내용34','글쓴이34');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목35','내용35','글쓴이35');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목36','내용36','글쓴이36');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목37','내용37','글쓴이37');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목38','내용38','글쓴이38');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목39','내용39','글쓴이39');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목40','내용40','글쓴이40');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목41','내용41','글쓴이41');


-- product_category 기본설정
-- 채소
insert into PRODUCT_CATEGORY(main_category, sub_category) values ( '907', '008');
insert into PRODUCT_CATEGORY(main_category, sub_category) values ( '907', '001');
insert into PRODUCT_CATEGORY(main_category, sub_category) values ( '907', '002');
-- 과일
insert into PRODUCT_CATEGORY(main_category, sub_category) values ( '908', '008');
insert into PRODUCT_CATEGORY(main_category, sub_category) values ( '908', '006');
insert into PRODUCT_CATEGORY(main_category, sub_category) values ( '908', '001');
-- 수산
insert into PRODUCT_CATEGORY(main_category, sub_category) values ( '909', '010');
insert into PRODUCT_CATEGORY(main_category, sub_category) values ( '909', '001');
insert into PRODUCT_CATEGORY(main_category, sub_category) values ( '909', '009');
-- 정육
insert into PRODUCT_CATEGORY(main_category, sub_category) values ( '910', '001');
insert into PRODUCT_CATEGORY(main_category, sub_category) values ( '910', '007');
insert into PRODUCT_CATEGORY(main_category, sub_category) values ( '910', '002');
-- 국
insert into PRODUCT_CATEGORY(main_category, sub_category) values ( '911', '001');
insert into PRODUCT_CATEGORY(main_category, sub_category) values ( '911', '006');
insert into PRODUCT_CATEGORY(main_category, sub_category) values ( '911', '002');

-- product 기본 설정
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CONTENT_SUMMARY, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE, SALE_UNIT, WEIGHT, DELIVERY_CLASSIFICATION, ORIGIN_COUNTRY, PACKING_TYPE) VALUES('친환경_당근',0,'InStock',0,'신선하고 깔끔하게 쓰는 양파(1개/100g)', TO_CHAR(SYSTIMESTAMP-0, 'YYYY-MM-DD HH:MI:SS.FF3'), 1, 70, '1개', '100g 내외', '샛별배송/택배배송', '국내산', '냉장, 종이포장');
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('친환경_대파',1000,'InStock',1,TO_CHAR(SYSTIMESTAMP-1, 'YYYY-MM-DD HH:MI:SS.FF3'), 1, 95);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('친환경_시금치',2000,'InStock',2,TO_CHAR(SYSTIMESTAMP-2, 'YYYY-MM-DD HH:MI:SS.FF3'), 1, 718);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('유기농_달수_고구마',3000,'InStock',3,TO_CHAR(SYSTIMESTAMP-3, 'YYYY-MM-DD HH:MI:SS.FF3'), 2, 529);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('친환경_세척_당근',4000,'InStock',4,TO_CHAR(SYSTIMESTAMP-4, 'YYYY-MM-DD HH:MI:SS.FF3'), 2, 63380);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('친환경_햇_감자',5000,'InStock',5,TO_CHAR(SYSTIMESTAMP-5, 'YYYY-MM-DD HH:MI:SS.FF3'), 2, 27316);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('유기농_베이비_채소',6000,'InStock',6,TO_CHAR(SYSTIMESTAMP-6, 'YYYY-MM-DD HH:MI:SS.FF3'), 3, 177);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('친환경_부추',7000,'InStock',7,TO_CHAR(SYSTIMESTAMP-7, 'YYYY-MM-DD HH:MI:SS.FF3'), 3, 149);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('친환경_쌈채소_모둠',8000,'InStock',8,TO_CHAR(SYSTIMESTAMP-8, 'YYYY-MM-DD HH:MI:SS.FF3'), 3, 102);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('게르마늄_무농약_컬러_방울토마토',9000,'InStock',9,TO_CHAR(SYSTIMESTAMP-9, 'YYYY-MM-DD HH:MI:SS.FF3'), 4, 3380);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('무농약_토마토',10000,'InStock',10,TO_CHAR(SYSTIMESTAMP-10, 'YYYY-MM-DD HH:MI:SS.FF3'), 4, 110);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('유기농_바나나',11000,'InStock',11,TO_CHAR(SYSTIMESTAMP-11, 'YYYY-MM-DD HH:MI:SS.FF3'), 4, 79);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('GAP_유명산지_머스크_멜론',12000,'InStock',12,TO_CHAR(SYSTIMESTAMP-12, 'YYYY-MM-DD HH:MI:SS.FF3'), 5, 27230);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('국산_깐밤',13000,'InStock',13,TO_CHAR(SYSTIMESTAMP-13, 'YYYY-MM-DD HH:MI:SS.FF3'), 5, 13677);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('부드러운_황도_복숭아',14000,'InStock',14,TO_CHAR(SYSTIMESTAMP-14, 'YYYY-MM-DD HH:MI:SS.FF3'), 5, 81815);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[선물세트]_자연마을_GAP_사과_세트',15000,'InStock',15,TO_CHAR(SYSTIMESTAMP-15, 'YYYY-MM-DD HH:MI:SS.FF3'), 6, 7702);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[선물세트]_청도_반건시',16000,'InStock',16,TO_CHAR(SYSTIMESTAMP-16, 'YYYY-MM-DD HH:MI:SS.FF3'), 6, 45426);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[해말린]_야자대추',17000,'InStock',17,TO_CHAR(SYSTIMESTAMP-17, 'YYYY-MM-DD HH:MI:SS.FF3'), 6, 3672);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[대흥]_간편하게_손질된_데친_참문어',18000,'InStock',18,TO_CHAR(SYSTIMESTAMP-18, 'YYYY-MM-DD HH:MI:SS.FF3'), 7, 83196);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[대흥]_담백한_동해안_손질_골뱅이살',19000,'InStock',19,TO_CHAR(SYSTIMESTAMP-19, 'YYYY-MM-DD HH:MI:SS.FF3'), 7, 83197);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[해원에스디]_신안군수_품질보증_생물새우',20000,'InStock',20,TO_CHAR(SYSTIMESTAMP-20, 'YYYY-MM-DD HH:MI:SS.FF3'), 7, 82945);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[선물세트]_강원도황태채포세트',21000,'InStock',21,TO_CHAR(SYSTIMESTAMP-21, 'YYYY-MM-DD HH:MI:SS.FF3'), 8, 83019);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[선물세트]_제주_갈치_고등어',22000,'InStock',22,TO_CHAR(SYSTIMESTAMP-22, 'YYYY-MM-DD HH:MI:SS.FF3'), 8, 83021);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[선물세트]_프리미엄_영광_굴비_세트',23000,'InStock',23,TO_CHAR(SYSTIMESTAMP-23, 'YYYY-MM-DD HH:MI:SS.FF3'), 8, 83020);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[이호]_참조기_550g내외(6~8미,_냉장)',24000,'InStock',24,TO_CHAR(SYSTIMESTAMP-24, 'YYYY-MM-DD HH:MI:SS.FF3'), 9, 68356);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('냉동_[법성포참맛]_대용량_영광굴비_1.2kg(20마리)_(냉동)_국내산',25000,'InStock',25,TO_CHAR(SYSTIMESTAMP-25, 'YYYY-MM-DD HH:MI:SS.FF3'), 9, 48540);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('냉동_[법성포참맛]_더_커진_프리미엄_영광굴비_110g(냉동)_국내산',26000,'InStock',26,TO_CHAR(SYSTIMESTAMP-26, 'YYYY-MM-DD HH:MI:SS.FF3'), 9, 48539);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[일상味소]_다짐육_200g(냉장)',27000,'InStock',27,TO_CHAR(SYSTIMESTAMP-27, 'YYYY-MM-DD HH:MI:SS.FF3'), 10, 6176);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[일상味소]_육전용_200g_(냉동)',28000,'InStock',28,TO_CHAR(SYSTIMESTAMP-28, 'YYYY-MM-DD HH:MI:SS.FF3'), 10, 27132);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[일상味소]_차돌박이_(냉동)',29000,'InStock',29,TO_CHAR(SYSTIMESTAMP-29, 'YYYY-MM-DD HH:MI:SS.FF3'), 10, 6175);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[델리치오]_호주산_목초육_안심_스테이크_250g(냉장)',30000,'InStock',30,TO_CHAR(SYSTIMESTAMP-30, 'YYYY-MM-DD HH:MI:SS.FF3'), 11, 47857);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[델리치오]_호주산_안심_찹스테이크_250g(냉장)',31000,'InStock',31,TO_CHAR(SYSTIMESTAMP-31, 'YYYY-MM-DD HH:MI:SS.FF3'), 11, 47858);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[미트엔조이]_호주산_목초_안심_스테이크_150g(냉장)',32000,'InStock',32,TO_CHAR(SYSTIMESTAMP-32, 'YYYY-MM-DD HH:MI:SS.FF3'), 11, 62204);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[돈마루]_한돈_삼겹살_2종_(냉장)',33000,'InStock',33,TO_CHAR(SYSTIMESTAMP-33, 'YYYY-MM-DD HH:MI:SS.FF3'), 12, 6021);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[돈마루]_한돈_앞다리살_2종_(냉장)',34000,'InStock',34,TO_CHAR(SYSTIMESTAMP-34, 'YYYY-MM-DD HH:MI:SS.FF3'), 12, 6023);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[해올림]_무항생제_삼겹살_2종_(냉장)',35000,'InStock',35,TO_CHAR(SYSTIMESTAMP-35, 'YYYY-MM-DD HH:MI:SS.FF3'), 12, 1653);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[벽제갈비]_한우_설렁탕_&_양곰탕_&_곰탕',36000,'InStock',36,TO_CHAR(SYSTIMESTAMP-36, 'YYYY-MM-DD HH:MI:SS.FF3'), 13, 1235);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[서강유업]_가족을_위한_사골곰탕',37000,'InStock',37,TO_CHAR(SYSTIMESTAMP-37, 'YYYY-MM-DD HH:MI:SS.FF3'), 13, 12950);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[앤쿡]_무항생제_어린이_한우_사골_곰국',38000,'InStock',38,TO_CHAR(SYSTIMESTAMP-38, 'YYYY-MM-DD HH:MI:SS.FF3'), 13, 11633);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[Everyday]_군산갑오징어_삼겹살볶음_(냉동)',39000,'InStock',39,TO_CHAR(SYSTIMESTAMP-39, 'YYYY-MM-DD HH:MI:SS.FF3'), 14 ,12847);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[강민구셰프의_밍글스]_대게장_새우_먹물_파스타',40000,'InStock',40,TO_CHAR(SYSTIMESTAMP-40, 'YYYY-MM-DD HH:MI:SS.FF3'), 14, 67376);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[콜린스_다이닝]_뿌리채소_비건만두',41000,'InStock',41,TO_CHAR(SYSTIMESTAMP-41, 'YYYY-MM-DD HH:MI:SS.FF3'), 14, 67162);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[진가네반찬]_순한_진미채볶음',42000,'InStock',42,TO_CHAR(SYSTIMESTAMP-42, 'YYYY-MM-DD HH:MI:SS.FF3'), 15, 11284);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[진가네반찬]_우엉채조림',43000,'InStock',43,TO_CHAR(SYSTIMESTAMP-43, 'YYYY-MM-DD HH:MI:SS.FF3'), 15, 13165);
INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE, PRODUCT_CATEGORY_ID, PRODUCT_CODE) VALUES('[진가네반찬]_지리멸치볶음',44000,'InStock',44,TO_CHAR(SYSTIMESTAMP-44, 'YYYY-MM-DD HH:MI:SS.FF3'), 15, 11278);



-- product_review 기본 설정
INSERT INTO LEVEL (SALE_PERCENT) VALUES('20');
INSERT INTO Member (LOGIN_ID, PASSWORD, NAME, EMAIL, PHONE_NUMBER, GENDER, BIRTH, LEVEL_ID, private_info, ad_sms, ad_email) VALUES('a', '$2a$10$KdMcrhifvyv9DVUIKGWbYu6IquPdWyNpaKTXj8JMEjn2jR8cD5uK2', '글쓴이1','이메일1','폰번호1','Male','생일1', '1', false, false, false);
INSERT INTO Member (LOGIN_ID, PASSWORD, NAME, EMAIL, PHONE_NUMBER, GENDER, BIRTH, LEVEL_ID, private_info, ad_sms, ad_email) VALUES('b', '$2a$10$.vrxEGpYWQXTDBROjpon8e9VkLXoQ1SnrPtLJr7iKttG80ivIz8.G', '글쓴이2','이메일2','폰번호2','Female','생일2', '1', false, false, false);
INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목1','내용1', '1', '1');
INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목2','내용2', '1', '1');
--INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목3','내용3', '1', '1');
--INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목4','내용4', '1', '1');
--INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목5','내용5', '2', '1');
--INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목6','내용6', '2', '1');
--INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목7','내용7', '2', '1');
--INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목8','내용8', '3', '1');
--INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목9','내용9', '3', '1');
--INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목10','내용10', '3', '1');
--INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목11','내용11', '4', '1');


-- cart 기본 설정
INSERT INTO Cart (member_id, product_id, count) VALUES('1', '1', 4);
INSERT INTO Cart (member_id, product_id, count) VALUES('1', '2', 3);
INSERT INTO Cart (member_id, product_id, count) VALUES('2', '2', 2);


-- event 기본 설정
INSERT INTO EVENT (FILE_CODE, FILE_NAME, CLASSIFICATION) VALUES('345', 'GoodsList1.PNG', 'Products');
INSERT INTO EVENT (FILE_CODE, FILE_NAME, CLASSIFICATION) VALUES('346', 'GoodsList2.PNG', 'Products');
INSERT INTO EVENT (FILE_CODE, FILE_NAME, CLASSIFICATION) VALUES('samsung', 'EventList1.PNG', 'NonProducts');
INSERT INTO EVENT (FILE_CODE, FILE_NAME, CLASSIFICATION) VALUES('test', 'EventList2.PNG', 'NonProducts');

-- productCategory 기본 설정
INSERT INTO PRODUCT_CATEGORY(MAIN_CATEGORY, SUB_CATEGORY) VALUES( '907', '008');

-- coupon 기본 설정
INSERT INTO COUPON(NAME, EXPIRATION_DATE, DISCOUNT_PERCENT, DISCOUNT_AMOUNT, CODE) VALUES('테스트 쿠폰', TO_CHAR(SYSTIMESTAMP + 30, 'YYYY-MM-DD HH:MI:SS.FF3'),'20', '0', 'test');
