-- freqQuestion 기본 설정
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목1!','내용내용1!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목2!','내용내용2!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목3!','내용내용3!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목4!','내용내용4!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목5!','내용내용5!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목6!','내용내용6!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목7!','내용내용7!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목8!','내용내용8!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목9!','내용내용!9');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목10!','내용내용10!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목11!','내용내용11!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목12!','내용내용12!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목13!','내용내용13!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목14!','내용내용14!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목15!','내용내용15!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목16!','내용내용16!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목17!','내용내용17!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목18!','내용내용18!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목19!','내용내용19!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목20!','내용내용20!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목21!','내용내용21!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목22!','내용내용22!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목23!','내용내용23!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목24!','내용내용24!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목25!','내용내용25!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목26!','내용내용26!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목27!','내용내용27!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목28!','내용내용28!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목29!','내용내용29!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목30!','내용내용30!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목31!','내용내용31!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목32!','내용내용32!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목33!','내용내용33!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목34!','내용내용34!');
insert into FREQ_QUESTION (CATEGORY, TITLE, CONTENT) values('테스트 카테고리','제목35!','내용내용35!');

-- notification 기본 설정
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목1','내용1','글쓴이1');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목2','내용2','글쓴이2');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목3','내용3','글쓴이3');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목4','내용4','글쓴이4');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목5','내용5','글쓴이5');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목6','내용6','글쓴이6');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목7','내용7','글쓴이7');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목8','내용8','글쓴이8');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목9','내용9','글쓴이9');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목10','내용10','글쓴이10');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목11','내용11','글쓴이11');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목12','내용12','글쓴이12');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목13','내용13','글쓴이13');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목14','내용14','글쓴이14');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목15','내용15','글쓴이15');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목16','내용16','글쓴이16');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목17','내용17','글쓴이17');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목18','내용18','글쓴이18');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목19','내용19','글쓴이19');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목20','내용20','글쓴이20');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목21','내용21','글쓴이21');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목22','내용22','글쓴이22');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목23','내용23','글쓴이23');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목24','내용24','글쓴이24');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목25','내용25','글쓴이25');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목26','내용26','글쓴이26');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목27','내용27','글쓴이27');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목28','내용28','글쓴이28');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목29','내용29','글쓴이29');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목30','내용30','글쓴이30');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목31','내용31','글쓴이31');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목32','내용32','글쓴이32');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목33','내용33','글쓴이33');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목34','내용34','글쓴이34');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목35','내용35','글쓴이35');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목36','내용36','글쓴이36');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목37','내용37','글쓴이37');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목38','내용38','글쓴이38');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목39','내용39','글쓴이39');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목40','내용40','글쓴이40');
insert into NOTIFICATION (TITLE, CONTENT, WRITER) values('제목41','내용41','글쓴이41');



-- product 기본 설정
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품0',0,'InStock',0,TO_CHAR(SYSTIMESTAMP-0, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품1',1000,'InStock',1,TO_CHAR(SYSTIMESTAMP-1, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품2',2000,'InStock',2,TO_CHAR(SYSTIMESTAMP-2, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품3',3000,'InStock',3,TO_CHAR(SYSTIMESTAMP-3, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품4',4000,'InStock',4,TO_CHAR(SYSTIMESTAMP-4, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품5',5000,'InStock',5,TO_CHAR(SYSTIMESTAMP-5, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품6',6000,'InStock',6,TO_CHAR(SYSTIMESTAMP-6, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품7',7000,'InStock',7,TO_CHAR(SYSTIMESTAMP-7, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품8',8000,'InStock',8,TO_CHAR(SYSTIMESTAMP-8, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품9',9000,'InStock',9,TO_CHAR(SYSTIMESTAMP-9, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품10',10000,'InStock',10,TO_CHAR(SYSTIMESTAMP-10, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품11',11000,'InStock',11,TO_CHAR(SYSTIMESTAMP-11, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품12',12000,'InStock',12,TO_CHAR(SYSTIMESTAMP-12, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품13',13000,'InStock',13,TO_CHAR(SYSTIMESTAMP-13, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품14',14000,'InStock',14,TO_CHAR(SYSTIMESTAMP-14, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품15',15000,'InStock',15,TO_CHAR(SYSTIMESTAMP-15, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품16',16000,'InStock',16,TO_CHAR(SYSTIMESTAMP-16, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품17',17000,'InStock',17,TO_CHAR(SYSTIMESTAMP-17, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품18',18000,'InStock',18,TO_CHAR(SYSTIMESTAMP-18, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품19',19000,'InStock',19,TO_CHAR(SYSTIMESTAMP-19, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품20',20000,'InStock',20,TO_CHAR(SYSTIMESTAMP-20, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품21',21000,'InStock',21,TO_CHAR(SYSTIMESTAMP-21, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품22',22000,'InStock',22,TO_CHAR(SYSTIMESTAMP-22, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품23',23000,'InStock',23,TO_CHAR(SYSTIMESTAMP-23, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품24',24000,'InStock',24,TO_CHAR(SYSTIMESTAMP-24, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품25',25000,'InStock',25,TO_CHAR(SYSTIMESTAMP-25, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품26',26000,'InStock',26,TO_CHAR(SYSTIMESTAMP-26, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품27',27000,'InStock',27,TO_CHAR(SYSTIMESTAMP-27, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품28',28000,'InStock',28,TO_CHAR(SYSTIMESTAMP-28, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품29',29000,'InStock',29,TO_CHAR(SYSTIMESTAMP-29, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품30',30000,'InStock',30,TO_CHAR(SYSTIMESTAMP-30, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품31',31000,'InStock',31,TO_CHAR(SYSTIMESTAMP-31, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품32',32000,'InStock',32,TO_CHAR(SYSTIMESTAMP-32, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품33',33000,'InStock',33,TO_CHAR(SYSTIMESTAMP-33, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품34',34000,'InStock',34,TO_CHAR(SYSTIMESTAMP-34, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품35',35000,'InStock',35,TO_CHAR(SYSTIMESTAMP-35, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품36',36000,'InStock',36,TO_CHAR(SYSTIMESTAMP-36, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품37',37000,'InStock',37,TO_CHAR(SYSTIMESTAMP-37, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품38',38000,'InStock',38,TO_CHAR(SYSTIMESTAMP-38, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품39',39000,'InStock',39,TO_CHAR(SYSTIMESTAMP-39, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품40',40000,'InStock',40,TO_CHAR(SYSTIMESTAMP-40, 'YYYY-MM-DD HH:MI:SS.FF3'));
--INSERT INTO PRODUCT (NAME, PRICE, STATUS, DISCOUNT_PERCENT, CREATED_DATE) VALUES('상품41',41000,'InStock',41,TO_CHAR(SYSTIMESTAMP-41, 'YYYY-MM-DD HH:MI:SS.FF3'));



-- product_review 기본 설정
--INSERT INTO LEVEL (SALE_PERCENT) VALUES('20');
--INSERT INTO Member (PASSWORD, NAME, EMAIL, PHONE_NUMBER, GENDER, ADDRESS, BIRTH, LEVEL_ID) VALUES('a', '글쓴이1','이메일1','폰번호1','Male','집주소1','생일1', '1');
--INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목1','내용1', '1', '1');
--INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목2','내용2', '1', '1');
--INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목3','내용3', '1', '1');
--INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목4','내용4', '1', '1');
--INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목5','내용5', '2', '1');
--INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목6','내용6', '2', '1');
--INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목7','내용7', '2', '1');
--INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목8','내용8', '3', '1');
--INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목9','내용9', '3', '1');
--INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목10','내용10', '3', '1');
--INSERT INTO PRODUCT_REVIEW (TITLE, CONTENT, PRODUCT_ID, MEMBER_ID) VALUES('제목11','내용11', '4', '1');


-- event 기본 설정
INSERT INTO EVENT (FILE_CODE, FILE_NAME, CLASSIFICATION) VALUES('345', 'GoodsList1.PNG', 'Products');
INSERT INTO EVENT (FILE_CODE, FILE_NAME, CLASSIFICATION) VALUES('346', 'GoodsList2.PNG', 'Products');
INSERT INTO EVENT (FILE_CODE, FILE_NAME, CLASSIFICATION) VALUES('samsung', 'EventList1.PNG', 'NonProducts');
INSERT INTO EVENT (FILE_CODE, FILE_NAME, CLASSIFICATION) VALUES('test', 'EventList2.PNG', 'NonProducts');
